version: "3.8"

services:
  acbr-api:
    build: .
    container_name: meu-acbr
    ports:
      - "3001:3001"
    volumes:
      - ./temp:/app/temp
      - ./logs:/app/logs
    environment:
      - DISPLAY=:1 # Garante que o Xvfb use o display 
      - TZ=America/Porto_Velho
    restart: unless-stopped